version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: abdelillah
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: promotion_marjane
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/promotion_marjane
      SPRING_DATASOURCE_USERNAME: abdelillah
      SPRING_DATASOURCE_PASSWORD: pass123

volumes:
  postgres-data: